# -*- coding: utf-8 -*-
"""Factors Influencing Survival on the Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LS-lrvfkMUYKSEFcCEKG-i5WijsFzT8_

# Identifying Factors Influencing Survival on the Titanic

**Import relevant packages**
"""

from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path1 = ('/content/drive/MyDrive/gender_submission.csv')
file_path2 = ('/content/drive/MyDrive/train.csv')

df1 = pd.read_csv(file_path1)
df2 = pd.read_csv(file_path2)

df2

print(df1['PassengerId'].nunique(), df2['PassengerId'].nunique())

common_passenger_ids = set(df1['PassengerId']).intersection(set(df2['PassengerId']))
print(f"Common PassengerIds: {len(common_passenger_ids)}")

print(df1['PassengerId'].dtype, df2['PassengerId'].dtype)

df1['PassengerId'] = df1['PassengerId'].astype(str)
df2['PassengerId'] = df2['PassengerId'].astype(str)

print(df1['PassengerId'].dtype, df2['PassengerId'].dtype)

df1['PassengerId'] = df1['PassengerId'].astype(str)
df2['PassengerId'] = df2['PassengerId'].astype(str)

merged_inner = pd.merge(df1, df2, on='PassengerId', how='inner')
print(merged_inner.head())

only_in_df1 = df1[~df1['PassengerId'].isin(df2['PassengerId'])]
print(only_in_df1.head())

only_in_df2 = df2[~df2['PassengerId'].isin(df1['PassengerId'])]
print(only_in_df2.head())

merged_outer = pd.merge(df1, df2, on='PassengerId', how='outer')
print(merged_outer.head())

merged_outer

"""**Understandong the dataset**

From this, we get that the variables are passengerID and Survived. Survived is categorial and opassengerID is numerical. There is no null values in either columns

**Data Cleaning**
"""

merged_outer.isnull().sum()

merged_outer.drop(columns=['Survived_x'], inplace=True)

missing_data = merged_outer.isnull().sum()
print(missing_data)

merged_cleaned = merged_outer.dropna(how='any')

merged_cleaned

"""**Exploratory Data Analysis**"""

merged_cleaned.groupby('Sex')['Survived_y'].mean().plot(kind='bar', title='Survival Rate by Gender')

merged_cleaned.groupby('Pclass')['Survived_y'].mean().plot(kind='bar', title='Survival Rate by Class')

merged_cleaned['Age Group'] = pd.cut(df['Age'], bins=[0, 12, 20, 35, 60, np.inf], labels=['Child', 'Teen', 'Adult', 'Middle-Aged', 'Senior'])
merged_cleaned.groupby('Age Group')['Survived_y'].mean().plot(kind='bar', title='Survival Rate by Age Group')

"""**Bivarite Analysis**"""

import seaborn as sns
sns.boxplot(x='Survived_y', y='Fare', data=merged_cleaned)

merged_cleaned.groupby('Embarked')['Survived_y'].mean().plot(kind='bar', title='Survival Rate by Embarkation Point')

"""**Correlational Analysis**"""

corr = merged_cleaned[['Age', 'Fare', 'Pclass', 'Survived_y']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.show()